/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.cjstehno.ersatz.socket;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ErsatzSocketTest {

}
